# Generated by Django 4.2 on 2025-04-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_custom_field', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Issue'), ('RETURN', 'Return')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='brnch_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('branch_logo', models.ImageField(null=True, upload_to='')),
                ('probation_period_days', models.IntegerField(default=0)),
                ('br_start_date', models.DateField(null=True)),
                ('br_is_active', models.BooleanField(default=True)),
                ('br_city', models.CharField(max_length=50)),
                ('br_pincode', models.CharField(max_length=20)),
                ('br_branch_nmbr_1', models.CharField(max_length=20, unique=True)),
                ('br_branch_nmbr_2', models.CharField(blank=True, max_length=20, null=True)),
                ('br_branch_mail', models.EmailField(max_length=254)),
                ('br_created_at', models.DateTimeField(auto_now_add=True)),
                ('br_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('policy_file', models.FileField(upload_to='policies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ctgry_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgry_title', models.CharField(max_length=50)),
                ('ctgry_code', models.CharField(max_length=50, unique=True)),
                ('ctgry_description', models.CharField(max_length=200)),
                ('ctgry_created_at', models.DateTimeField(auto_now_add=True)),
                ('ctgry_updated_at', models.DateTimeField(auto_now=True)),
                ('ctgry_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='dept_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=50, unique=True)),
                ('dept_description', models.CharField(max_length=200)),
                ('dept_created_at', models.DateTimeField(auto_now_add=True)),
                ('dept_updated_at', models.DateTimeField(auto_now=True)),
                ('dept_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='desgntn_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgntn_job_title', models.CharField(max_length=50)),
                ('desgntn_code', models.CharField(max_length=50, unique=True)),
                ('desgntn_description', models.CharField(max_length=200)),
                ('desgntn_created_at', models.DateTimeField(auto_now_add=True)),
                ('desgntn_updated_at', models.DateTimeField(auto_now=True)),
                ('desgntn_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='OrganisationManager.brnch_mstr')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.fiscalyear')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general_request', 'General Request'), ('leave_request', 'Leave Request')], max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('current_number', models.IntegerField(default=0)),
                ('total_length', models.IntegerField(default=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_numbering_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
