# Generated by Django 5.0.6 on 2024-12-17 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('EmpManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_custom_field', models.CharField(max_length=100, null=True)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('asset_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='OrganisationManager.assetmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Issue'), ('RETURN', 'Return')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='OrganisationManager.assetmaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transactions', to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='brnch_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('branch_logo', models.ImageField(null=True, upload_to='')),
                ('notification_period_days', models.IntegerField()),
                ('br_start_date', models.DateField(null=True)),
                ('br_is_active', models.BooleanField(default=True)),
                ('br_city', models.CharField(max_length=50)),
                ('br_pincode', models.CharField(max_length=20)),
                ('br_branch_nmbr_1', models.CharField(max_length=20, unique=True)),
                ('br_branch_nmbr_2', models.CharField(blank=True, max_length=20, null=True)),
                ('br_branch_mail', models.EmailField(max_length=254, unique=True)),
                ('br_created_at', models.DateTimeField(auto_now_add=True)),
                ('br_updated_at', models.DateTimeField(auto_now=True)),
                ('br_country', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Core.cntry_mstr')),
                ('br_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('br_state_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Core.state_mstr')),
                ('br_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('branch_users', models.ManyToManyField(related_name='branches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ctgry_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgry_title', models.CharField(max_length=50)),
                ('ctgry_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ctgry_description', models.CharField(max_length=200)),
                ('ctgry_created_at', models.DateTimeField(auto_now_add=True)),
                ('ctgry_updated_at', models.DateTimeField(auto_now=True)),
                ('ctgry_is_active', models.BooleanField(default=True)),
                ('ctgry_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('ctgry_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dept_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dept_description', models.CharField(max_length=200)),
                ('dept_created_at', models.DateTimeField(auto_now_add=True)),
                ('dept_updated_at', models.DateTimeField(auto_now=True)),
                ('dept_is_active', models.BooleanField(default=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrganisationManager.brnch_mstr')),
                ('dept_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dept_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('policy_file', models.FileField(upload_to='policies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.brnch_mstr')),
                ('specific_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.ctgry_master')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.dept_master')),
            ],
        ),
        migrations.CreateModel(
            name='desgntn_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgntn_job_title', models.CharField(max_length=50)),
                ('desgntn_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('desgntn_description', models.CharField(max_length=200)),
                ('desgntn_created_at', models.DateTimeField(auto_now_add=True)),
                ('desgntn_updated_at', models.DateTimeField(auto_now=True)),
                ('desgntn_is_active', models.BooleanField(default=True)),
                ('desgntn_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('desgntn_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='document_numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_numbering', models.BooleanField()),
                ('preffix', models.CharField(max_length=50, unique=True)),
                ('suffix', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('start_number', models.IntegerField()),
                ('current_number', models.IntegerField()),
                ('end_number', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.ctgry_master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='OrganisationManager.brnch_mstr')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.fiscalyear')),
            ],
            options={
                'unique_together': {('fiscal_year', 'period_number')},
            },
        ),
    ]
