# Generated by Django 4.2 on 2025-04-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmpManagement', '0002_initial'),
        ('Core', '0001_initial'),
        ('OrganisationManager', '0001_initial'),
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumbering',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.leave_type'),
        ),
        migrations.AddField(
            model_name='documentnumbering',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_numbering_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desgntn_master',
            name='desgntn_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desgntn_master',
            name='desgntn_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dept_master',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='dept_master',
            name='dept_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dept_master',
            name='dept_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctgry_master',
            name='ctgry_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctgry_master',
            name='ctgry_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.ctgry_master'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.dept_master'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='specific_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brnch_mstr',
            name='br_country',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Core.cntry_mstr'),
        ),
        migrations.AddField(
            model_name='brnch_mstr',
            name='br_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brnch_mstr',
            name='br_state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.state_mstr'),
        ),
        migrations.AddField(
            model_name='brnch_mstr',
            name='br_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='OrganisationManager.assetmaster'),
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transactions', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='assetmaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset_customfieldvalue',
            name='asset_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='OrganisationManager.assetmaster'),
        ),
        migrations.AddField(
            model_name='asset_customfieldvalue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('fiscal_year', 'period_number')},
        ),
        migrations.AddConstraint(
            model_name='documentnumbering',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'general_request')), fields=('branch_id', 'type'), name='unique_general_request_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='documentnumbering',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'leave_request')), fields=('branch_id', 'leave_type'), name='unique_leave_request_per_branch_leave_type'),
        ),
    ]
