# Generated by Django 5.0.4 on 2024-06-07 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0003_brnch_mstr_br_start_date_brnch_mstr_branch_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='document_numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_numbering', models.BooleanField()),
                ('preffix', models.CharField(max_length=50, unique=True)),
                ('suffix', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('start_number', models.IntegerField()),
                ('current_number', models.IntegerField()),
                ('end_number', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.ctgry_master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
