# Generated by Django 5.0.4 on 2024-06-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0004_document_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
