# Generated by Django 5.0.4 on 2024-07-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0005_fiscalyear_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctgry_master',
            old_name='created_at',
            new_name='ctgry_created_at',
        ),
        migrations.RenameField(
            model_name='ctgry_master',
            old_name='created_by',
            new_name='ctgry_created_by',
        ),
        migrations.RenameField(
            model_name='ctgry_master',
            old_name='is_active',
            new_name='ctgry_is_active',
        ),
        migrations.RenameField(
            model_name='ctgry_master',
            old_name='catogary_title',
            new_name='ctgry_title',
        ),
        migrations.RenameField(
            model_name='ctgry_master',
            old_name='updated_at',
            new_name='ctgry_updated_at',
        ),
        migrations.RenameField(
            model_name='ctgry_master',
            old_name='updated_by',
            new_name='ctgry_updated_by',
        ),
        migrations.RenameField(
            model_name='dept_master',
            old_name='created_at',
            new_name='dept_created_at',
        ),
        migrations.RenameField(
            model_name='dept_master',
            old_name='created_by',
            new_name='dept_created_by',
        ),
        migrations.RenameField(
            model_name='dept_master',
            old_name='description',
            new_name='dept_description',
        ),
        migrations.RenameField(
            model_name='dept_master',
            old_name='is_active',
            new_name='dept_is_active',
        ),
        migrations.RenameField(
            model_name='dept_master',
            old_name='updated_at',
            new_name='dept_updated_at',
        ),
        migrations.RenameField(
            model_name='dept_master',
            old_name='updated_by',
            new_name='dept_updated_by',
        ),
        migrations.RenameField(
            model_name='desgntn_master',
            old_name='created_at',
            new_name='desgntn_created_at',
        ),
        migrations.RenameField(
            model_name='desgntn_master',
            old_name='created_by',
            new_name='desgntn_created_by',
        ),
        migrations.RenameField(
            model_name='desgntn_master',
            old_name='description',
            new_name='desgntn_description',
        ),
        migrations.RenameField(
            model_name='desgntn_master',
            old_name='is_active',
            new_name='desgntn_is_active',
        ),
        migrations.RenameField(
            model_name='desgntn_master',
            old_name='job_title',
            new_name='desgntn_job_title',
        ),
        migrations.RenameField(
            model_name='desgntn_master',
            old_name='updated_at',
            new_name='desgntn_updated_at',
        ),
        migrations.RenameField(
            model_name='desgntn_master',
            old_name='updated_by',
            new_name='desgntn_updated_by',
        ),
        migrations.AddField(
            model_name='ctgry_master',
            name='ctgry_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dept_master',
            name='dept_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='desgntn_master',
            name='desgntn_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
