# Generated by Django 5.0.6 on 2024-09-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0110_emailtemplate_use_common_template'),
        ('OrganisationManager', '0007_companypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='specific_employees',
            field=models.ManyToManyField(blank=True, to='EmpManagement.emp_master'),
        ),
    ]
