# Generated by Django 5.0.6 on 2024-09-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0008_companypolicy_specific_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypolicy',
            name='specific_employees',
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.ctgry_master'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='OrganisationManager.dept_master'),
        ),
    ]
