# Generated by Django 4.2 on 2024-11-20 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0012_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brnch_mstr',
            name='br_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
