# Generated by Django 4.2 on 2024-11-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0013_alter_brnch_mstr_br_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brnch_mstr',
            name='branch_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
