# Generated by Django 4.2 on 2024-11-20 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cntry_mstr',
            name='country_code',
        ),
        migrations.AddField(
            model_name='cntry_mstr',
            name='timezone',
            field=models.CharField(default=django.utils.timezone.now, help_text="Set timezone as per IANA timezone database format, e.g., 'America/New_York'", max_length=100),
            preserve_default=False,
        ),
    ]
