# Generated by Django 5.0.4 on 2024-06-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weekend_calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calander_title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('calendar_code', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('monday', models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday'), ('leave', 'leave')], max_length=10, null=True)),
                ('tuesday', models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday'), ('leave', 'leave')], max_length=10, null=True)),
                ('wednesday', models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday'), ('leave', 'leave')], max_length=10, null=True)),
                ('thursday', models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday'), ('leave', 'leave')], max_length=10, null=True)),
                ('friday', models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday'), ('leave', 'leave')], max_length=10, null=True)),
                ('saturday', models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday'), ('leave', 'leave')], max_length=10, null=True)),
                ('sunday', models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday'), ('leave', 'leave')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assign_weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(choices=[('branch', 'Branch'), ('department', 'Department'), ('category', 'Category'), ('employee', 'Employee')], max_length=20, null=True)),
                ('weekend_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.weekend_calendar')),
            ],
        ),
    ]
