# Generated by Django 5.0.4 on 2024-06-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0005_fiscalyear_end_date'),
        ('calendars', '0002_assign_weekend_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_weekend',
            name='target_id',
        ),
        migrations.AddField(
            model_name='assign_weekend',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='assign_weekend',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrganisationManager.dept_master'),
        ),
        migrations.AddField(
            model_name='assign_weekend',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrganisationManager.ctgry_master'),
        ),
    ]
