# Generated by Django 5.0.4 on 2024-06-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0011_emp_master_emp_weekend_calendar'),
        ('OrganisationManager', '0005_fiscalyear_end_date'),
        ('calendars', '0004_holiday_alter_assign_weekend_related_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_weekend',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='EmpManagement.emp_master'),
        ),
        migrations.RemoveField(
            model_name='assign_weekend',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='assign_weekend',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assign_weekend',
            name='department',
        ),
        migrations.AlterField(
            model_name='assign_weekend',
            name='related_to',
            field=models.CharField(choices=[('branch', 'Branch'), ('department', 'Department'), ('category', 'Category'), ('employee', 'Employee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assign_weekend',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='assign_weekend',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.dept_master'),
        ),
        migrations.AddField(
            model_name='assign_weekend',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.ctgry_master'),
        ),
    ]
