# Generated by Django 5.0.4 on 2024-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_remove_weekend_calendar_calander_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekenddetail',
            name='month_of_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
