# Generated by Django 5.0.4 on 2024-07-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_weekend_calendar_friday_weekend_calendar_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekenddetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
