# Generated by Django 5.0.4 on 2024-07-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0009_weekenddetail_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekenddetail',
            options={'ordering': ['pk']},
        ),
    ]
