# Generated by Django 5.0.6 on 2024-12-10 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True, unique=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='document_report/')),
            ],
            options={
                'permissions': (('export_document_report', 'Can export doc report'),),
            },
        ),
        migrations.CreateModel(
            name='DocExpEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('Employee Notification', 'Employee Notification'), ('ESS User Notification', 'ESS User Notification')], max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('request_created', 'Request Created'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('use_common_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField'), ('text', 'TextField'), ('checkbox', 'CheckboxField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('checkbox_values', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100, null=True)),
                ('field_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDocuments_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpFamily_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpJobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_jh_from_date', models.DateField()),
                ('emp_jh_end_date', models.DateField()),
                ('emp_jh_company_name', models.CharField(max_length=50)),
                ('emp_jh_designation', models.CharField(max_length=50)),
                ('emp_jh_leaving_salary_permonth', models.FloatField()),
                ('emp_jh_reason', models.CharField(max_length=100)),
                ('emp_jh_years_experiance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpJobHistory_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('reason', models.CharField(default='its ook', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLangSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMarketingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProgramSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, choices=[('Language Skill', 'Language Skill'), ('Marketing Skill', 'Marketing Skill'), ('Programming Language Skill', 'Programming Language Skill')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_qualification', models.CharField(max_length=50)),
                ('emp_qf_instituition', models.CharField(max_length=50)),
                ('emp_qf_year', models.DateField()),
                ('emp_qf_subject', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpQualification_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('total', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRequestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True, unique=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='general_report/')),
            ],
            options={
                'permissions': (('export_general_request_report', 'Can export general request report'),),
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiry', models.IntegerField(default=7)),
                ('days_after_expiry', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True, unique=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='employee_report/')),
            ],
            options={
                'permissions': (('export_report', 'Can export report'),),
            },
        ),
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('use_common_workflow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEmpNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_sl_no', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('emp_doc_number', models.IntegerField()),
                ('emp_doc_issued_date', models.DateField()),
                ('emp_doc_expiry_date', models.DateField()),
                ('emp_doc_document', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.document_type')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emp_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef_member_name', models.CharField(max_length=50)),
                ('emp_relation', models.CharField(max_length=50)),
                ('ef_company_expence', models.FloatField()),
                ('ef_date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emp_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('emp_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, null=True)),
                ('emp_date_of_birth', models.DateField(blank=True, null=True)),
                ('emp_personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('emp_company_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('emp_mobile_number_1', models.CharField(blank=True, null=True)),
                ('emp_mobile_number_2', models.CharField(blank=True, null=True)),
                ('emp_city', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_permenent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_present_address', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_status', models.BooleanField(blank=True, default=True, null=True)),
                ('emp_joined_date', models.DateField(blank=True, null=True)),
                ('emp_date_of_confirmation', models.DateField(blank=True, null=True)),
                ('emp_relegion', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('emp_blood_group', models.CharField(blank=True, max_length=50)),
                ('emp_nationality', models.CharField(blank=True, null=True)),
                ('emp_marital_status', models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('divorced', 'divorced'), ('widow', 'widow')], max_length=10, null=True)),
                ('emp_father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('epm_ot_applicable', models.BooleanField(blank=True, default=False, null=True)),
                ('is_ess', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_created_by1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
