# Generated by Django 4.2 on 2025-04-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='document_report/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('export_document_report', 'Can export doc report'),),
            },
        ),
        migrations.CreateModel(
            name='DocExpEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('Employee Notification', 'Employee Notification'), ('ESS User Notification', 'ESS User Notification')], max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('request_created', 'Request Created'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField'), ('text', 'TextField'), ('checkbox', 'CheckboxField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('checkbox_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_doc_number', models.CharField(max_length=50, unique=True)),
                ('emp_doc_issued_date', models.DateField()),
                ('emp_doc_expiry_date', models.DateField()),
                ('emp_doc_document', models.FileField(blank=True, null=True, upload_to='emp_documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef_member_name', models.CharField(max_length=50)),
                ('emp_relation', models.CharField(max_length=50)),
                ('ef_company_expence', models.FloatField()),
                ('ef_date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=50, unique=True)),
                ('emp_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, null=True)),
                ('emp_date_of_birth', models.DateField(blank=True, null=True)),
                ('emp_personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_mobile_number_1', models.CharField(blank=True, null=True)),
                ('emp_mobile_number_2', models.CharField(blank=True, null=True)),
                ('emp_city', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_permenent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_present_address', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_status', models.BooleanField(blank=True, default=True, null=True)),
                ('emp_joined_date', models.DateField()),
                ('emp_date_of_confirmation', models.DateField(blank=True, null=True)),
                ('emp_profile_pic', models.ImageField(blank=True, null=True, upload_to='emp_profile_pic/')),
                ('emp_blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_marital_status', models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('divorced', 'divorced'), ('widow', 'widow')], max_length=10, null=True)),
                ('emp_father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('epm_ot_applicable', models.BooleanField(blank=True, default=False, null=True)),
                ('is_ess', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDocuments_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100, null=True, unique=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField'), ('text', 'TextField'), ('checkbox', 'CheckboxField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('checkbox_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpFamily_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100, null=True, unique=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField'), ('text', 'TextField'), ('checkbox', 'CheckboxField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('checkbox_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpJobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_jh_from_date', models.DateField()),
                ('emp_jh_end_date', models.DateField()),
                ('emp_jh_company_name', models.CharField(max_length=50)),
                ('emp_jh_designation', models.CharField(max_length=50)),
                ('emp_jh_leaving_salary_permonth', models.FloatField()),
                ('emp_jh_reason', models.CharField(max_length=100)),
                ('emp_jh_years_experiance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpJobHistory_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100, null=True, unique=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField'), ('text', 'TextField'), ('checkbox', 'CheckboxField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('checkbox_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('reason', models.CharField(default='its ook', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('route_code', models.CharField(blank=True, max_length=20, null=True)),
                ('iban_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLangSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMarketingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProgramSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_qualification', models.CharField(max_length=50)),
                ('emp_qf_instituition', models.CharField(max_length=50)),
                ('emp_qf_year', models.DateField()),
                ('emp_qf_subject', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpQualification_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100, null=True, unique=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField'), ('text', 'TextField'), ('checkbox', 'CheckboxField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('checkbox_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fam_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('total', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('request_document', models.FileField(blank=True, null=True, upload_to='generalrequest_documents/')),
                ('created_at_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRequestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='general_report/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('export_general_request_report', 'Can export general request report'),),
            },
        ),
        migrations.CreateModel(
            name='JobHistory_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiry', models.IntegerField(default=7)),
                ('days_after_expiry', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEmpNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('selected_employees', models.ManyToManyField(blank=True, to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('use_common_workflow', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='employee_report/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('export_report', 'Can export report'),),
            },
        ),
        migrations.CreateModel(
            name='Qualification_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_custom_field', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='EmpManagement.empqualification')),
            ],
        ),
    ]
