# Generated by Django 5.0.4 on 2024-05-22 05:23

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('OrganisationManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('emp_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('emp_date_of_birth', models.DateField(blank=True, null=True)),
                ('emp_personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('emp_mobile_number_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('emp_mobile_number_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('emp_city', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_permenent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_present_address', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_status', models.BooleanField(blank=True, default=True, null=True)),
                ('emp_hired_date', models.DateField(blank=True, null=True)),
                ('emp_active_date', models.DateField(blank=True, null=True)),
                ('emp_relegion', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('emp_blood_group', models.CharField(blank=True, max_length=50)),
                ('emp_nationality', models.CharField(blank=True, null=True)),
                ('emp_marital_status', models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Other')], max_length=1, null=True)),
                ('emp_father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_posting_location', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('epm_ot_applicable', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_created_by1', to=settings.AUTH_USER_MODEL)),
                ('emp_branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr')),
                ('emp_country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.cntry_mstr')),
                ('emp_ctgry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.ctgry_master')),
                ('emp_dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.dept_master')),
                ('emp_desgntn_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.desgntn_master')),
                ('emp_languages', models.ManyToManyField(blank=True, null=True, to='Core.languagemaster')),
                ('emp_state_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.state_mstr')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_updated_by1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emp_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef_member_name', models.CharField(max_length=50)),
                ('emp_relation', models.CharField(max_length=50)),
                ('ef_company_expence', models.FloatField()),
                ('ef_date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_family', to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_doc_number', models.IntegerField()),
                ('emp_doc_issued_date', models.DateField()),
                ('emp_doc_expiry_date', models.DateField()),
                ('emp_doc_document', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.document_type')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_documents', to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='EmpJobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_jh_from_date', models.DateField()),
                ('emp_jh_end_date', models.DateField()),
                ('emp_jh_company_name', models.CharField(max_length=50)),
                ('emp_jh_designation', models.CharField(max_length=50)),
                ('emp_jh_leaving_salary_permonth', models.FloatField()),
                ('emp_jh_reason', models.CharField(max_length=100)),
                ('emp_jh_years_experiance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_job_history', to='EmpManagement.emp_master')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('reason', models.CharField(default='its ook', max_length=150)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leaverequest', to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='EmpQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_qualification', models.CharField(max_length=50)),
                ('emp_qf_instituition', models.CharField(max_length=50)),
                ('emp_qf_year', models.DateField()),
                ('emp_qf_subject', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_qualification', to='EmpManagement.emp_master')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_documents')),
            ],
        ),
    ]
