# Generated by Django 5.0.6 on 2024-12-17 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('EmpManagement', '0001_initial'),
        ('OrganisationManager', '0001_initial'),
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_master',
            name='emp_branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.cntry_mstr'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_ctgry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.ctgry_master'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.dept_master'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_desgntn_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.desgntn_master'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.state_mstr'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_weekend_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.weekend_calendar'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='holiday_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.holiday_calendar'),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_updated_by1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_master',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emp_family',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_family', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='emp_documents',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_documents', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='emp_customfieldvalue',
            name='emp_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='empdocuments_customfield',
            name='emp_documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_documents'),
        ),
        migrations.AddField(
            model_name='empfamily_customfield',
            name='emp_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_custom_fields', to='EmpManagement.emp_family'),
        ),
        migrations.AddField(
            model_name='empjobhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empjobhistory',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_job_history', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='empjobhistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empjobhistory_customfield',
            name='emp_job_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobhistory_customfields', to='EmpManagement.empjobhistory'),
        ),
        migrations.AddField(
            model_name='empleaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leaverequest', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='employeelangskill',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_lang_skills', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='employeemarketingskill',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_market_skills', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='employeeprogramskill',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_prgrm_skills', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_skills', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='empqualification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empqualification',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_qualification', to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='empqualification',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empqualification_customfield',
            name='emp_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.empqualification'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='approval',
            name='general_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='EmpManagement.generalrequest'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='language_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.languageskill'),
        ),
        migrations.AddField(
            model_name='employeelangskill',
            name='language_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.languageskill'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='marketing_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.marketingskill'),
        ),
        migrations.AddField(
            model_name='employeemarketingskill',
            name='marketing_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.marketingskill'),
        ),
        migrations.AddField(
            model_name='notification',
            name='document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_documents'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='programming_language_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.programminglanguageskill'),
        ),
        migrations.AddField(
            model_name='employeeprogramskill',
            name='program_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.programminglanguageskill'),
        ),
        migrations.AddField(
            model_name='requestnotification',
            name='recipient_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master'),
        ),
        migrations.AddField(
            model_name='requestnotification',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.requesttype'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='request_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='EmpManagement.requesttype'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='EmpManagement.requesttype'),
        ),
        migrations.AddField(
            model_name='selectedempnotify',
            name='selected_employees',
            field=models.ManyToManyField(blank=True, to='EmpManagement.emp_master'),
        ),
        migrations.AddConstraint(
            model_name='commonworkflow',
            constraint=models.UniqueConstraint(fields=('level',), name='unique_common_workflow_level'),
        ),
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together={('level', 'request_type')},
        ),
    ]
