# Generated by Django 5.0.4 on 2024-05-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0003_alter_emp_master_emp_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_master',
            name='is_ess',
            field=models.BooleanField(default=False),
        ),
    ]
