# Generated by Django 5.0.4 on 2024-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0004_emp_master_is_ess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], max_length=10, null=True),
        ),
    ]
