# Generated by Django 5.0.4 on 2024-05-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0005_alter_emp_master_emp_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_master',
            name='emp_posting_location',
        ),
    ]
