# Generated by Django 5.0.4 on 2024-05-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0007_languageskill_marketingskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='value',
            field=models.CharField(blank=True, choices=[('Language Skill', 'Language Skill'), ('Marketing Skill', 'Marketing Skill'), ('Programming Skill', 'Programming Skill')], default=None, max_length=100, null=True),
        ),
    ]
