# Generated by Django 5.0.4 on 2024-06-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0008_alter_employeeskill_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeSkill', to='EmpManagement.emp_master'),
        ),
    ]
