# Generated by Django 5.0.4 on 2024-06-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0010_requesttype_generalrequest'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_master',
            name='emp_weekend_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.weekend_calendar'),
        ),
    ]
