# Generated by Django 5.0.6 on 2024-07-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0012_emp_master_holiday_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='document_report/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRequestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='general_report/')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('report_data', models.FileField(blank=True, null=True, upload_to='employee_report/')),
            ],
            options={
                'permissions': (('export_report', 'Can export report'),),
            },
        ),
        migrations.RemoveField(
            model_name='generalrequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_skills', to='EmpManagement.emp_master'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='value',
            field=models.CharField(blank=True, choices=[('Language Skill', 'Language Skill'), ('Marketing Skill', 'Marketing Skill'), ('Programming Language Skill', 'Programming Language Skill')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('general_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='EmpManagement.generalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('emp_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDocuments_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('emp_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_documents')),
            ],
        ),
        migrations.CreateModel(
            name='EmpFamily_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('emp_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_custom_fields', to='EmpManagement.emp_family')),
            ],
        ),
        migrations.CreateModel(
            name='EmpJobHistory_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('emp_job_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobhistory_customfields', to='EmpManagement.empjobhistory')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLangSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_lang_skills', to='EmpManagement.emp_master')),
                ('language_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.languageskill')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMarketingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_market_skills', to='EmpManagement.emp_master')),
                ('marketing_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.marketingskill')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProgramSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_prgrm_skills', to='EmpManagement.emp_master')),
                ('program_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.programminglanguageskill')),
            ],
        ),
        migrations.CreateModel(
            name='EmpQualification_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True)),
                ('dropdown_values', models.JSONField(blank=True, null=True)),
                ('radio_values', models.JSONField(blank=True, null=True)),
                ('emp_qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.empqualification')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='EmpManagement.requesttype')),
            ],
            options={
                'unique_together': {('level', 'request_type')},
            },
        ),
    ]
