# Generated by Django 5.0.6 on 2024-07-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0016_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
