# Generated by Django 5.0.6 on 2024-07-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0019_alter_requestnotification_recipient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_customfield',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField')], max_length=20, null=True),
        ),
    ]
