# Generated by Django 5.0.6 on 2024-07-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('EmpManagement', '0022_emp_documents_emp_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_documents',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.document_type'),
        ),
    ]
