# Generated by Django 5.0.6 on 2024-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0023_alter_emp_documents_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_master',
            name='emp_company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
