# Generated by Django 5.0.6 on 2024-07-26 08:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0024_emp_master_emp_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_mobile_number_1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_mobile_number_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
