# Generated by Django 5.0.6 on 2024-07-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0025_alter_emp_master_emp_mobile_number_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.TextField(blank=True, null=True)),
                ('emp_custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='EmpManagement.emp_customfield')),
                ('emp_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='EmpManagement.emp_master')),
            ],
        ),
    ]
