# Generated by Django 5.0.6 on 2024-07-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0030_alter_emp_customfield_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfield',
            name='emp_master',
        ),
    ]
