# Generated by Django 5.0.6 on 2024-07-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0033_remove_emp_customfield_emp_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_customfield',
            name='emp_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_master'),
        ),
    ]
