# Generated by Django 5.0.6 on 2024-07-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0034_emp_customfield_emp_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfield',
            name='emp_master',
        ),
    ]
