# Generated by Django 5.0.6 on 2024-07-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0035_remove_emp_customfield_emp_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_mobile_number_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_mobile_number_2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
