# Generated by Django 5.0.6 on 2024-07-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0036_alter_emp_master_emp_mobile_number_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc_report',
            options={'permissions': (('export_report', 'Can export report'),)},
        ),
        migrations.AlterModelOptions(
            name='generalrequestreport',
            options={'permissions': (('export_report', 'Can export report'),)},
        ),
    ]
