# Generated by Django 5.0.6 on 2024-08-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0039_alter_doc_report_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.doc_report')),
            ],
        ),
    ]
