# Generated by Django 5.0.6 on 2024-08-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0040_filtereddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilteredData',
        ),
    ]
