# Generated by Django 5.0.6 on 2024-08-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0045_emp_master_custom_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfieldvalue',
            name='emp_master',
        ),
        migrations.AddField(
            model_name='emp_customfieldvalue',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='emp_customfieldvalue',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
