# Generated by Django 5.0.6 on 2024-08-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0047_remove_emp_master_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteredreportdata',
            name='report',
        ),
        migrations.DeleteModel(
            name='FilteredGeneralReportData',
        ),
        migrations.DeleteModel(
            name='FilteredReportData',
        ),
    ]
