# Generated by Django 5.0.6 on 2024-08-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0048_remove_filteredreportdata_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfieldvalue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='emp_customfieldvalue',
            name='object_id',
        ),
        migrations.AddField(
            model_name='emp_customfieldvalue',
            name='emp_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='EmpManagement.emp_master'),
        ),
    ]
