# Generated by Django 5.0.6 on 2024-08-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0049_remove_emp_customfieldvalue_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotification',
            name='general_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.generalrequest'),
        ),
    ]
