# Generated by Django 5.0.6 on 2024-08-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0050_requestnotification_general_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestnotification',
            name='general_request',
        ),
    ]
