# Generated by Django 5.0.6 on 2024-08-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0051_remove_requestnotification_general_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='created_at',
            new_name='created_at_date',
        ),
    ]
