# Generated by Django 5.0.6 on 2024-08-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0052_rename_created_at_approval_created_at_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='created_at_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='generalrequest',
            old_name='created_at',
            new_name='created_at_date',
        ),
    ]
