# Generated by Django 5.0.6 on 2024-08-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0053_rename_created_at_date_approval_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalrequest',
            old_name='created_at_date',
            new_name='created_at',
        ),
    ]
