# Generated by Django 5.0.6 on 2024-08-14 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0055_rename_created_at_generalrequest_created_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_customfieldvalue',
            name='emp_custom_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='EmpManagement.emp_customfield'),
        ),
    ]
