# Generated by Django 5.0.6 on 2024-08-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0059_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
