# Generated by Django 5.0.6 on 2024-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0060_alter_emailverification_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfieldvalue',
            name='emp_custom_field',
        ),
        migrations.AddField(
            model_name='emp_customfieldvalue',
            name='field_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
