# Generated by Django 5.0.6 on 2024-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0062_remove_emp_customfieldvalue_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_customfieldvalue',
            name='emp_custom_field_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
