# Generated by Django 5.0.6 on 2024-08-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0063_emp_customfieldvalue_emp_custom_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfieldvalue',
            name='emp_custom_field_name',
        ),
    ]
