# Generated by Django 5.0.6 on 2024-08-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0065_remove_emp_customfieldvalue_emp_custom_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_customfieldvalue',
            old_name='field_name',
            new_name='emp_custom_field',
        ),
    ]
