# Generated by Django 5.0.6 on 2024-08-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0066_rename_field_name_emp_customfieldvalue_emp_custom_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_customfieldvalue',
            old_name='emp_custom_field',
            new_name='field_name',
        ),
    ]
