# Generated by Django 5.0.6 on 2024-08-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0067_rename_emp_custom_field_emp_customfieldvalue_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_customfieldvalue',
            old_name='field_name',
            new_name='emp_custom_field',
        ),
    ]
