# Generated by Django 5.0.6 on 2024-08-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0069_rename_field_name_emp_customfield_emp_custom_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_customfield',
            name='emp_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_master'),
        ),
    ]
