# Generated by Django 5.0.6 on 2024-08-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0071_approval_note_for_next_approver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='comments',
            new_name='note',
        ),
    ]
