# Generated by Django 5.0.6 on 2024-08-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0072_rename_comments_approval_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfield',
            name='emp_master',
        ),
    ]
