# Generated by Django 5.0.6 on 2024-08-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0075_emp_customfield_emp_master_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_master',
            old_name='user_id',
            new_name='users',
        ),
    ]
