# Generated by Django 5.0.6 on 2024-08-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0076_rename_user_id_emp_master_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_customfield',
            old_name='emp_master_fields',
            new_name='checkbox_values',
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField'), ('date', 'DateField'), ('text', 'TextField'), ('checkbox', 'CheckboxField')], max_length=20, null=True),
        ),
    ]
