# Generated by Django 5.0.6 on 2024-08-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0077_rename_emp_master_fields_emp_customfield_checkbox_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='note_for_next_approver',
        ),
    ]
