# Generated by Django 5.0.6 on 2024-09-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0079_emailconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
