# Generated by Django 5.0.6 on 2024-09-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0081_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc_Report',
        ),
    ]
