# Generated by Django 5.0.6 on 2024-09-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0083_doc_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralRequestReport',
        ),
    ]
