# Generated by Django 5.0.6 on 2024-09-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0088_alter_selectedempnotify_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedempnotify',
            old_name='employee',
            new_name='selected_ess_user',
        ),
        migrations.RemoveField(
            model_name='selectedempnotify',
            name='receive_notifications',
        ),
    ]
