# Generated by Django 5.0.6 on 2024-09-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0090_alter_selectedempnotify_selected_ess_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='s_user',
        ),
    ]
