# Generated by Django 5.0.6 on 2024-09-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0091_remove_notification_s_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedempnotify',
            name='selected_ess_user',
        ),
        migrations.AddField(
            model_name='selectedempnotify',
            name='selected_ess_users',
            field=models.ManyToManyField(blank=True, to='EmpManagement.emp_master'),
        ),
    ]
