# Generated by Django 5.0.6 on 2024-09-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0094_documentremindersettings'),
        ('OrganisationManager', '0006_rename_created_at_ctgry_master_ctgry_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiry', models.IntegerField(default=7)),
                ('days_after_expiry', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentReminderSettings',
        ),
    ]
