# Generated by Django 5.0.6 on 2024-09-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0095_notificationsettings_delete_documentremindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_documents',
            name='expired_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emp_documents',
            name='first_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emp_documents',
            name='second_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
