# Generated by Django 5.0.6 on 2024-09-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0096_emp_documents_expired_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_documents',
            name='expired_notification_sent',
        ),
        migrations.RemoveField(
            model_name='emp_documents',
            name='first_notification_sent',
        ),
        migrations.RemoveField(
            model_name='emp_documents',
            name='second_notification_sent',
        ),
    ]
