# Generated by Django 5.0.6 on 2024-09-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0097_remove_emp_documents_expired_notification_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocExpEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
