# Generated by Django 5.0.6 on 2024-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0099_alter_generalrequest_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedempnotify',
            name='selected_ess_user',
        ),
        migrations.AddField(
            model_name='selectedempnotify',
            name='selected_employees',
            field=models.ManyToManyField(blank=True, to='EmpManagement.emp_master'),
        ),
    ]
