# Generated by Django 5.0.6 on 2024-09-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0101_alter_approvallevel_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttype',
            name='use_common_workflow',
        ),
    ]
