# Generated by Django 5.0.6 on 2024-09-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0102_remove_requesttype_use_common_workflow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together={('level', 'request_type')},
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='EmpManagement.requesttype'),
        ),
        migrations.RemoveField(
            model_name='approvallevel',
            name='common_workflow',
        ),
    ]
