# Generated by Django 5.0.6 on 2024-09-23 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0103_alter_approvallevel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallevel',
            name='is_common_workflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='EmpManagement.requesttype'),
        ),
    ]
