# Generated by Django 5.0.6 on 2024-09-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0104_approvallevel_is_common_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='use_common_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
