# Generated by Django 5.0.6 on 2024-09-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0107_commonworkflow_unique_common_workflow_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='email_template',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='request_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='EmpManagement.requesttype'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], max_length=50, null=True),
        ),
    ]
