# Generated by Django 5.0.6 on 2024-10-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0111_employeemachinemapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeMachineMapping',
        ),
    ]
