# Generated by Django 5.0.6 on 2024-10-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0112_delete_employeemachinemapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
