# Generated by Django 4.2 on 2024-11-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0113_delete_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('divorced', 'divorced'), ('widow', 'widow')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeYearlyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('daily_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_calendar', to='EmpManagement.emp_master')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('emp', 'year')},
            },
        ),
    ]
