# Generated by Django 4.2 on 2024-11-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0114_alter_emp_master_emp_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeYearlyCalendar',
        ),
    ]
