# Generated by Django 5.0.6 on 2024-09-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_remove_selectedessuser_selected_ess_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedEssUser',
        ),
    ]
