# Generated by Django 5.0.4 on 2024-07-17 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0012_emp_master_holiday_calendar'),
        ('LeaveManagement', '0002_dtype'),
        ('OrganisationManager', '0006_rename_created_at_ctgry_master_ctgry_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual', models.BooleanField(default=False)),
                ('accrual_rate', models.FloatField(default=0, help_text='Accrual rate per period (e.g., days/months)')),
                ('frequency', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=20)),
                ('day', models.PositiveIntegerField(default=1)),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=3)),
                ('round_of', models.CharField(choices=[('nearest_lowest', 'nearest_lowest'), ('nearest_highest', 'nearest_highest')], max_length=20)),
                ('prorate_accrual', models.BooleanField(default=False)),
                ('prorate_start', models.CharField(default='start_of_policy', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='applicablity_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], null=True)),
                ('branch', models.ManyToManyField(blank=True, null=True, to='OrganisationManager.brnch_mstr')),
                ('department', models.ManyToManyField(blank=True, null=True, to='OrganisationManager.dept_master')),
                ('designation', models.ManyToManyField(blank=True, null=True, to='OrganisationManager.desgntn_master')),
                ('role', models.ManyToManyField(blank=True, null=True, to='OrganisationManager.ctgry_master')),
            ],
        ),
        migrations.CreateModel(
            name='emp_leave_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('openings', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.emp_leave_balance')),
            ],
        ),
        migrations.CreateModel(
            name='leave_entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_after', models.PositiveIntegerField(default=0)),
                ('effective_after_unit', models.CharField(choices=[('year', 'Year'), ('month', 'Month')], default='month', max_length=10)),
                ('effective_after_from', models.CharField(choices=[('date_of_joining', 'Date of Joining'), ('date_of_confirmation', 'Date of Confirmation')], default='date_of_joining', max_length=20)),
                ('accrual_settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.accrualsettings')),
            ],
        ),
        migrations.CreateModel(
            name='leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='leave_images/')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=10)),
                ('unit', models.CharField(choices=[('days', 'days'), ('hours', 'hours')], max_length=10)),
                ('negative', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('allow_opening_balance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAccrualTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type')),
            ],
        ),
        migrations.CreateModel(
            name='ResetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=20)),
                ('day', models.PositiveIntegerField(default=31)),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Dec', max_length=3)),
                ('carry_forward', models.PositiveIntegerField(default=50)),
                ('carry_forward_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('encashment', models.PositiveIntegerField(default=50)),
                ('encashment_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type')),
            ],
        ),
        
        migrations.DeleteModel(
            name='dtype',
        ),
        migrations.AddField(
            model_name='leave_entitlement',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.AddField(
            model_name='emp_leave_balance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.AddField(
            model_name='applicablity_criteria',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.AddField(
            model_name='accrualsettings',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.AddField(
            model_name='leave_entitlement',
            name='reset_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.resetsettings'),
        ),
    ]
