# Generated by Django 5.0.4 on 2024-07-17 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0003_accrualsettings_applicablity_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
