# Generated by Django 5.0.6 on 2024-10-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0007_shift_employeeshift_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
