# Generated by Django 5.0.6 on 2024-10-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0009_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='shift',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='EmployeeShift',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
