# Generated by Django 5.0.6 on 2024-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0015_alter_shiftassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
