# Generated by Django 5.0.6 on 2024-10-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0017_remove_attendance_shift_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='location',
        ),
    ]
