# Generated by Django 5.0.6 on 2024-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0019_attendance_shift'),
        ('OrganisationManager', '0012_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.dept_master'),
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='designation',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.desgntn_master'),
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.ctgry_master'),
        ),
    ]
