# Generated by Django 5.0.6 on 2024-10-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0110_emailtemplate_use_common_template'),
        ('LeaveManagement', '0020_weeklyshiftschedule_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='employee',
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='EmpManagement.emp_master'),
        ),
    ]
