# Generated by Django 5.0.6 on 2024-10-08 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0023_attendance_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
