# Generated by Django 5.0.6 on 2024-10-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0112_delete_employeemachinemapping'),
        ('LeaveManagement', '0024_shift_break_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMachineMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=100, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
            ],
        ),
    ]
