# Generated by Django 5.0.6 on 2024-10-17 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0112_delete_employeemachinemapping'),
        ('LeaveManagement', '0026_leavereport'),
        ('OrganisationManager', '0012_delete_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='applicablity_critirea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], null=True)),
                ('branch', models.ManyToManyField(blank=True, to='OrganisationManager.brnch_mstr')),
                ('department', models.ManyToManyField(blank=True, to='OrganisationManager.dept_master')),
                ('designation', models.ManyToManyField(blank=True, to='OrganisationManager.desgntn_master')),
            ],
        ),
        migrations.CreateModel(
            name='employee_leave_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('dis_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='leave_accrual_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='leave_reset_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_date', models.DateField()),
                ('carry_forward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('encashment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reset_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
            ],
        ),
        migrations.RemoveField(
            model_name='accrualsettings',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leave_entitlement',
            name='accrual_settings',
        ),
        migrations.RemoveField(
            model_name='applicablity_criteria',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='applicablity_criteria',
            name='department',
        ),
        migrations.RemoveField(
            model_name='applicablity_criteria',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='applicablity_criteria',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='applicablity_criteria',
            name='role',
        ),
        migrations.DeleteModel(
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leave_entitlement',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leave_entitlement',
            name='reset_settings',
        ),
        migrations.RemoveField(
            model_name='leaveaccrualtransaction',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaveaccrualtransaction',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='resetsettings',
            name='leave_type',
        ),
        migrations.RenameField(
            model_name='leave_type',
            old_name='allow_opening_balance',
            new_name='allow_half_day',
        ),
        migrations.AddField(
            model_name='emp_leave_balance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leave_type',
            name='include_weekend_and_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emp_leave_balance',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave_type',
            name='type',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicablity_critirea',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.AddField(
            model_name='applicablity_critirea',
            name='role',
            field=models.ManyToManyField(blank=True, to='OrganisationManager.ctgry_master'),
        ),
        migrations.AddField(
            model_name='employee_leave_request',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.AddField(
            model_name='leave_accrual_transaction',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.AddField(
            model_name='leave_reset_transaction',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type'),
        ),
        migrations.DeleteModel(
            name='AccrualSettings',
        ),
        migrations.DeleteModel(
            name='applicablity_criteria',
        ),
        migrations.DeleteModel(
            name='EmployeeLeave',
        ),
        migrations.DeleteModel(
            name='leave_entitlement',
        ),
        migrations.DeleteModel(
            name='LeaveAccrualTransaction',
        ),
        migrations.DeleteModel(
            name='ResetSettings',
        ),
    ]
