# Generated by Django 5.0.6 on 2024-10-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0027_applicablity_critirea_employee_leave_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_after', models.PositiveIntegerField(default=0)),
                ('effective_after_unit', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'days')], default='months', max_length=10)),
                ('effective_after_from', models.CharField(choices=[('date_of_joining', 'Date of Joining'), ('date_of_confirmation', 'Date of Confirmation')], max_length=20)),
                ('accrual', models.BooleanField(default=False)),
                ('accrual_rate', models.FloatField(default=0, help_text='Accrual rate per period (e.g., days/months/yearly)')),
                ('accrual_frequency', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'days')], max_length=20)),
                ('accrual_month', models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=3, null=True)),
                ('accrual_day', models.CharField(choices=[('1st', '1st Day of the Month'), ('last', 'Last Day of the Month')], default='1st', max_length=10)),
                ('round_of', models.CharField(choices=[('nearest_lowest', 'nearest_lowest'), ('nearest_highest', 'nearest_highest')], max_length=20)),
                ('reset', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'days')], max_length=20)),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Dec', max_length=30)),
                ('day', models.CharField(choices=[('1st', '1st Day of the Month'), ('last', 'Last Day of the Month')], max_length=20)),
                ('carry_forward_choice', models.CharField(choices=[('carry_forward', 'carry forward'), ('carry_forward_with_expiry', 'carry forward with expiry')], max_length=100)),
                ('cf_value', models.PositiveIntegerField()),
                ('cf_unit_or_percentage', models.CharField(choices=[('percentage', 'percentage'), ('unit', 'unit')], max_length=50)),
                ('cf_max_limit', models.PositiveIntegerField()),
                ('cf_expires_in_value', models.PositiveIntegerField()),
                ('cf_time_choice', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'days')], max_length=20)),
                ('encashment_value', models.PositiveIntegerField(default=50)),
                ('encashment_unit_or_percentage', models.CharField(choices=[('percentage', 'percentage'), ('unit', 'unit')], max_length=50)),
                ('encashment_max_limit', models.PositiveIntegerField()),
                ('prorate_accrual', models.BooleanField(default=False, help_text='Enable prorate accrual for this leave type.')),
                ('prorate_type', models.CharField(blank=True, choices=[('start_of_policy', 'Start of Policy'), ('start_and_end_of_policy', 'Start and End of Policy'), ('do_not_prorate', 'Do not Prorate')], help_text='Prorate accrual type.', max_length=30, null=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.leave_type')),
            ],
        ),
    ]
