# Generated by Django 5.0.6 on 2024-10-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0030_lvapprovalnotify_lvemailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvapprovalnotify',
            old_name='recipient_user_user',
            new_name='recipient_user',
        ),
    ]
