# Generated by Django 5.0.6 on 2024-10-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0032_employee_leave_request_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_leave_request',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employee_leave_request',
            name='approved_on',
        ),
    ]
