# Generated by Django 5.0.6 on 2024-10-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0034_lvcommonworkflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='use_common_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
