# Generated by Django 5.0.6 on 2024-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0035_leave_type_use_common_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave_request',
            name='number_of_days',
            field=models.FloatField(default=1),
        ),
    ]
