# Generated by Django 4.2 on 2024-11-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0115_delete_employeeyearlycalendar'),
        ('LeaveManagement', '0041_lvbalancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeYearlyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('daily_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_calendar', to='EmpManagement.emp_master')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('emp', 'year')},
            },
        ),
    ]
