# Generated by Django 4.2 on 2024-11-20 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0042_employeeyearlycalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
